### PR TITLE
361 Add ResultPrinter Utility

### LINKED ISSUE #361: Add ResultPrinter utility
Incapsulate console output logic in `ResultPrinter` utility class.

### PR DESCRIPTION
**Pull request by netme**
Closes #361

### CODE REVIEW

**Comment by netme** [comment]
@maxim-tschumak could you please review?

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
@maxim-tschumak I've rebased it, could you please check again?

**Comment by maxim-tschumak** [comment]
> The command "go test -v -cover ./..." exited with 2. 

Can you please re-trigger the Travis build, @netme ?

**Comment by netme** [comment]
I think it's broken. Let me try to fix it :-)

**Comment by netme** [comment]
@maxim-tschumak , hopefully fixed now. Commit 7a83b54 introduced some module name changes in tests

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
