### PR TITLE
198 Move Fetching URL to Server

### LINKED ISSUE #198: Move fetch api definition feature to Zally API
The web ui currently does the fetching of an api definition which is given via an url by the user. The web ui implements this on server side in Node.

Let's discuss if we should change our Zally API to also accept links to api definition files. There are different ways of designing this:

- adding new endpoint only for urls
- adding new optional field in payload of current `api-violations` endpoint
- transparently accepting a link in current `api_definition`field

Looking for feedback from you, @netme @mkulak @rbarilani. Do you wanna have this in Zally API? And if yes, which design do you prefer?

### PR DESCRIPTION
**Pull request by netme**
Closes to #198

### CODE REVIEW

**Comment by mkulak** [comment]
Looks good so far. What's left?

**Comment by netme** [comment]
@mkulak , we probably need to discuss how to deal with YAML files in this case. And then we need a way to accept YAML via `api_definition` parameter for consistency reasons. 

Let's discuss it with @fmueller

**Comment by netme** [comment]
And seems to be I also broken a build 😹

**Comment by netme** [comment]
Ticket #221 is created

**Comment by netme** [comment]
Seems to be, there is currently a trouble with JPM, most probably need to restart Travis build afterwards. Locally tests are passing:

```bash
$ gradle clean build
:clean
:compileKotlin
Using kotlin incremental compilation
w: The '-d' option with a directory destination is ignored because '-module' is specified
:compileJava
:copyMainKotlinClasses
:processResources
:classes
:findMainClass
:jar
:bootRepackage
:assemble
:compileTestKotlin
Using kotlin incremental compilation
w: The '-d' option with a directory destination is ignored because '-module' is specified
:compileTestJava
:copyTestKotlinClasses
:processTestResources
:testClasses
:test
objc[67094]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x10f4b34c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x110df04e0). One of the two will be used. Which one is undefined.
2017-03-31 23:40:16.355  INFO 67094 --- [      Thread-18] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5502743e: startup date [Fri Mar 31 23:40:09 CEST 2017]; root of context hierarchy
2017-03-31 23:40:16.355  INFO 67094 --- [      Thread-16] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@53205304: startup date [Fri Mar 31 23:40:05 CEST 2017]; root of context hierarchy
2017-03-31 23:40:16.355  INFO 67094 --- [      Thread-37] o.s.w.c.s.GenericWebApplicationContext   : Closing org.springframework.web.context.support.GenericWebApplicationContext@621ae3ee: startup date [Fri Mar 31 23:40:12 CEST 2017]; root of context hierarchy
2017-03-31 23:40:16.356  INFO 67094 --- [      Thread-14] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@380c7396: startup date [Fri Mar 31 23:39:55 CEST 2017]; root of context hierarchy
:jacocoTestReport
:ktlint
:check
:build

BUILD SUCCESSFUL
```

**Comment by netme** [comment]
Will do CLI changes in a separate PR.

**Comment by fmueller** [comment]
👍

**Pull request merged**
