### PR TITLE
server: implement vendor extension to ignore rules by code (#406)

### PR DESCRIPTION
**Pull request by innokenty**
Example syntax:
```json
{
  "x-zally-ignore": [
    "M001",
    "M999"
  ],
  "swagger" : "2.0",
  ...
}
```

### CODE REVIEW

**Comment by innokenty** [comment]
Asked review from all the people, engaged in the conversation here: https://github.com/zalando-incubator/zally/issues/406#issuecomment-317413093

**Comment by maxim-tschumak** [comment]
@innokenty Have you looked at the `de.zalando.zally.rule.RulesPolicy`? I believe the implementation of these 2 functionalities should be combined:
1. configuring the server via the applicaiton configuration
2. configuring an api validation configuration via vendor extension field

Please check if it's possbile.

**Comment by innokenty** [comment]
Application configuration is already implemented. That's the `RulesPolicy` class you mentioned, that's right.

I wanted to implement parsing this vendor extension there as well, but faced a problem: it depends on the input file. We have two types of rules: json and swagger, and they get the api definition in different formats. That's why there are two implementations.

And if you take a closer look at my Kotlin code snippets in `JsonRule.accepts` and `SwaggerRule.accepts` — you can see that they are slightly different. One works with `JsonNode` and another one with `Swagger` object.

That's my story 👆 
Is that what you meant? What do you think?

**Comment by maxim-tschumak** [comment]
I see your point. I'm still not 100% ok with the design (static and dynamic configuration of which rules are exluded), but let's keep it like this for now and see how it develops. Thank you for the contribution!
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by innokenty** [comment]
Alright, thanks! I don't see a big conflict in there, those two configs serve absolutely different purposes: one disables a rule completely, because, I don't know.. It doesn't work properly. When the other config helps teams with not-standard compliant APIs still use zally with not much pain.

**Comment by innokenty** [comment]
I don't like that the code is duplicated between json and swagger implementations, but that looks unavoidable.

The duplicated ways to exclude rules look totally ok to me.

**Comment by maxim-tschumak** [comment]
There are two slightly different perspectives:
* **maintainer/operator/zally developer** doesn't want to remove a rule implementation if the respective guideline was removed from the [RESTful API Guidelines](http://zalando.github.io/restful-api-guidelines/).
* **zally user** with non-standard compliant APIs.


> The duplicated ways to exclude rules look totally ok to me.

Agree! :)

**Pull request merged**
