### PR TITLE
Separated rule implementations from infrastructure

### PR DESCRIPTION
**Pull request by roxspring**
As suggested in #569 I've moved rule implementations into a distinct sub-package so that infrastructure interfaces and classes can be easily seen and refactored for the Rule Sets effort.

### CODE REVIEW

**Comment by netme** [comment]
@roxspring thanks for your contribution. In general it's not a bad idea to separate the rule implementations, but the same time I'm not super convinced with `impl` package naming, it sounds a bit vintage to me and in general I somehow agree with answers in this Stackoverflow thread: https://stackoverflow.com/questions/1004980/should-interfaces-be-placed-in-a-separate-package 
Let's think a bit more carefully about this topic.

@maxim-tschumak , @maschleg what do you think about it?

**Comment by roxspring** [comment]
I'm not a big fan of the `impl` sub package name myself but I view it as a lesser crime than 48 classes of mixed responsibilities in a single package. Would have probably preferred a `rule` sub package but `rule.rule` seemed ugly. Perhaps splitting down technology lines and using a `swagger` sub package would be better?

As mentioned in #569 I figure it's a transitory move anyway - presumably we'll soon end up with separate packages and/or source trees to achieve the '"Zalando API Guidelines" and "Zally" Rule Sets are split up' acceptance criteria needed for #560.

**Comment by maxim-tschumak** [comment]
I also don't really like the `impl` name of the package. But I see a benefit of separating current rule/checks implementations and zally "core" functionality (interfaces, controller, configuration, etc.).
How do you feel about:
- Moving all non-rule-related stuff from `rule` package to new `core` package (I'm open to other names)
- Moving `util` package into the `rule` package.
This could be a good first step for #559.
@netme At some point, we have to separate interfaces declaration from the actual implementation of the rules.

**Comment by roxspring** [comment]
Happy to split Zally and Zalando rules in to separate sub packages as part of #575 if that's preferred.

**Pull request closed without merging**
