### PR TITLE
ZALLY-113 Introduce Checkstyle in CLI subproject

### PR DESCRIPTION
**Pull request by netme**
Related to #113 

🔋 

- Introduces Checkstyle
- Fixes issues found by Checkstyle 

Rules adjustments from dfbf1e2 to be discussed with @fmueller and @maxim-tschumak 

### How to test:
- Run `./gradlew check`
- Observe that only `Javadoc` issues left

### CODE REVIEW

**Comment by netme** [comment]
Here is an example output on Travis: https://travis-ci.org/zalando-incubator/zally/builds/194976852#L323

**Comment by netme** [comment]
Restarted builds after #118 got merged

**Comment by fmueller** [comment]
LGTM

We should align the ruleset to use afterwards in the next days, @netme

**Comment by fmueller** [comment]
👍

**Comment by netme** [comment]
@fmueller yes, makes complete sense. I wanted to open a discussion here. Right now it's a google rule set with 2 exceptions:

- Line length: 120 chars (to be aligned with IDEA defaults)
- Tab length: 4 chars (was before 2)

**Comment by netme** [comment]
@fmueller and to be 100% clear, Google standard requires docstrings. There are about 10 warnings now due to that. We should also agree if we are using them or not.

**Pull request merged**
