### PR TITLE
#69 CLI: Move Linting to Linter Class

### LINKED ISSUE #69: Make CLI's Main Class Leaner
Currently `Main` class of `cli` subproject is bloated with business logic.
Make it leaner.

### PR DESCRIPTION
**Pull request by netme**
Closes #69 

🔋 Small refactoring, increases test coverage

### CODE REVIEW

**Comment by fmueller** [comment]
You are introducing JMockit with this change. Since we are using Spring Boot on server side, there is already Mockito available in the server codebase. I wanted to kindly ask you if it would be much effort for you to rewrite your tests with Mockito. My intention is to keep the number of used libraries low - to make contributions easier.

**Comment by netme** [comment]
@fmueller, sure, I was just not sure which library is better to use and used `JMockit`. I will change it, thanks for the tip.

**Comment by netme** [comment]
@fmueller I've switched from JMockit to Mockito in a2e4d2b

**Comment by fmueller** [comment]
LGTM

**Comment by fmueller** [comment]
👍

**Pull request merged**
