### PR TITLE
#82 New Swagger Definition for Violation Grouping

### PR DESCRIPTION
**Pull request by netme**
Related to #82

### CODE REVIEW

**Comment by mkulak** [comment]
Do we have progress on the spec? I would really like to implement grouping (this will alow me to convert most of the stuff to K).

**Comment by fmueller** [comment]
Path field was added by @netme which looks good.

Open question for me is, do we wanna make grouping optional on the API by providing groupBy field, so that an API client can group by any field? Or just group by default by path? I'd prefer first solution as it is more flexible for later integration scenarios. What do you think @netme @mkulak?

Btw @mkulak I guess @netme wanted to implement the grouping. ;)

**Comment by mkulak** [comment]
@netme sorry, I misinterpret your intention. Keep on going with this task.

**Comment by netme** [comment]
@mkulak , @fmueller , I've just synced what we have in current API with the Swagger definition in 4f414f2 .

@fmueller , could you please provide a quick example? Would be great to group by specific field. I just thought to group by issue type, I think `title` field is good for that.  

I will continue working on the API design. @mkulak , if you wanna contribute to this topic, you are always welcome, we can sync tomorrow.

**Comment by mkulak** [comment]
Actually I realised that I'm out of sync with you guys on this topic. I will try to describe my thought on that and you will correct me.
Right now each rule generates multiple violations and output looks like this:
```
Found the following MUST violations
===================================

Use snake_case (never camelCase) for Query Parameters
        Query parameter 'merchant-id' does not use snake_case.
        http://zalando.github.io/restful-api-guidelines/naming/Naming.html#must-use-snakecase-never-camelcase-for-query-parameters

Use snake_case (never camelCase) for Query Parameters
        Query parameter 'merchant-id' does not use snake_case.
        http://zalando.github.io/restful-api-guidelines/naming/Naming.html#must-use-snakecase-never-camelcase-for-query-parameters

Define and Assign Access Rights (Scopes)
        (path: /merchants)
        No valid OAuth2 scope is defined for endpoint Get a list of merchants whose articles have ever been in the review queue.
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /merchants/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /meta/article_domains)
        No valid OAuth2 scope is defined for endpoint Get a list of article domains.
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Every Second Path Level To Be Parameter
        (path: /meta/article_domains)
        Every second path level must be a path parameter

Lowercase words with hyphens
        (path: /meta/article_domains)
        Use lowercase separate words with hyphens for path segments
        http://zalando.github.io/restful-api-guidelines/naming/Naming.html#must-use-lowercase-separate-words-with-hyphens-for-path-segments

Response As JSON Object
        (path: /meta/article_domains/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /meta/colors)
        No valid OAuth2 scope is defined for endpoint Get a list of colors.
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Every Second Path Level To Be Parameter
        (path: /meta/colors)
        Every second path level must be a path parameter

Response As JSON Object
        (path: /meta/colors/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /meta/commodity_groups)
        No valid OAuth2 scope is defined for endpoint Get a list of commodity groups.
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Every Second Path Level To Be Parameter
        (path: /meta/commodity_groups)
        Every second path level must be a path parameter

Lowercase words with hyphens
        (path: /meta/commodity_groups)
        Use lowercase separate words with hyphens for path segments
        http://zalando.github.io/restful-api-guidelines/naming/Naming.html#must-use-lowercase-separate-words-with-hyphens-for-path-segments

Response As JSON Object
        (path: /meta/commodity_groups/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /meta/size_grids)
        No valid OAuth2 scope is defined for endpoint Get a list of size grids.
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Every Second Path Level To Be Parameter
        (path: /meta/size_grids)
        Every second path level must be a path parameter

Lowercase words with hyphens
        (path: /meta/size_grids)
        Use lowercase separate words with hyphens for path segments
        http://zalando.github.io/restful-api-guidelines/naming/Naming.html#must-use-lowercase-separate-words-with-hyphens-for-path-segments

Response As JSON Object
        (path: /meta/size_grids/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /meta/tags)
        No valid OAuth2 scope is defined for endpoint Get a list of tags.
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Every Second Path Level To Be Parameter
        (path: /meta/tags)
        Every second path level must be a path parameter

Response As JSON Object
        (path: /meta/tags/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /queue/configs/{config-id})
        No valid OAuth2 scope is defined for endpoint Get the details for the given config ID.
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Every Second Path Level To Be Parameter
        (path: /queue/configs/{config-id})
        Every second path level must be a path parameter

Response As JSON Object
        (path: /queue/configs/{config-id}/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /queue/models)
        No valid OAuth2 scope is defined for endpoint Get all models to review for given merchant.
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Every Second Path Level To Be Parameter
        (path: /queue/models)
        Every second path level must be a path parameter

Response As JSON Object
        (path: /queue/models/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /queue/models/{model-id})
        No valid OAuth2 scope is defined for endpoint Get one model by given model id
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Every Second Path Level To Be Parameter
        (path: /queue/models/{model-id})
        Every second path level must be a path parameter

Response As JSON Object
        (path: /queue/models/{model-id}/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /queue/summaries)
        No valid OAuth2 scope is defined for endpoint Get the queue summary for the given merchant, if specified, or the total for all merchants, if none is specified.
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Every Second Path Level To Be Parameter
        (path: /queue/summaries)
        Every second path level must be a path parameter

Response As JSON Object
        (path: /queue/summaries/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /rejections)
        No valid OAuth2 scope is defined for endpoint Create a list of rejections and associate them with a given list of article configs
        http://zalando.github.io/restful-api-guidelines/security/Security.html

```

Messy and very WET (as opposed to DRY).
I'd prefer it to be grouped by name:

```
Found the following MUST violations
===================================

Use snake_case (never camelCase) for Query Parameters
        (path:
        /queue/models GET
        /queue/summaries GET)
        Query parameter 'merchant-id' does not use snake_case.
        http://zalando.github.io/restful-api-guidelines/naming/Naming.html#must-use-snakecase-never-camelcase-for-query-parameters

Lowercase words with hyphens
        (path:
        /meta/article_domains
        /meta/commodity_groups
        /meta/size_grids)
        Use lowercase separate words with hyphens for path segments
        http://zalando.github.io/restful-api-guidelines/naming/Naming.html#must-use-lowercase-separate-words-with-hyphens-for-path-segments

Define and Assign Access Rights (Scopes)
        (path:
        /meta/article_domains
        /meta/commodity_groups
        /queue/models
        /meta/colors
        /queue/configs/{config-id}
        /queue/summaries
        /meta/size_grids
        /queue/models/{model-id}
        /merchants
        /meta/tags
        /rejections)
        No valid OAuth2 scope is defined for endpoint
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Every Second Path Level To Be Parameter
        (path:
        /meta/article_domains
        /meta/commodity_groups
        /queue/models
        /meta/colors
        /queue/configs/{config-id}
        /queue/summaries
        /meta/size_grids
        /queue/models/{model-id}
        /meta/tags)
        Every second path level must be a path parameter

Response As JSON Object
        (path:
        /meta/article_domains/GET/200
        /meta/commodity_groups/GET/200
        /queue/models/GET/200
        /meta/colors/GET/200
        /queue/configs/{config-id}/GET/200
        /queue/summaries/GET/200
        /meta/size_grids/GET/200
        /queue/models/{model-id}/GET/200
        /merchants/GET/200
        /meta/tags/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility


Found the following SHOULD violations
=====================================

Limit number of Resources
        Number of paths (11) violates the limit of 8.
        http://zalando.github.io/restful-api-guidelines/resources/Resources.html#should-limit-number-of-resources

Pluralize Resource Names
        (path:
        /queue/models
        /queue/configs/{config-id}
        /queue/summaries
        /queue/models/{model-id})
        Resource name 'queue' is not pluralized (but we are not sure)
        http://zalando.github.io/restful-api-guidelines/naming/Naming.html#must-pluralize-resource-names


Summary:
========

MUST violations: 35
SHOULD violations: 5
COULD violations: 0
```

I found the latter much cleaner, concise and useful. I hope you agree with me on that point.
Regarding grouping on fields other than title: I don't see much value in it. Here is the output grouped by path:
```
Found the following MUST violations
===================================

Define and Assign Access Rights (Scopes)
        (path: /merchants)
        No valid OAuth2 scope is defined for endpoint Get a list of merchants whose articles have ever been in the review queue.
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /merchants/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
Every Second Path Level To Be Parameter
Lowercase words with hyphens
        (path: /meta/article_domains)
        No valid OAuth2 scope is defined for endpoint Get a list of article domains.
Every second path level must be a path parameter
Use lowercase separate words with hyphens for path segments
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /meta/article_domains/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
Every Second Path Level To Be Parameter
        (path: /meta/colors)
        No valid OAuth2 scope is defined for endpoint Get a list of colors.
Every second path level must be a path parameter
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /meta/colors/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
Every Second Path Level To Be Parameter
Lowercase words with hyphens
        (path: /meta/commodity_groups)
        No valid OAuth2 scope is defined for endpoint Get a list of commodity groups.
Every second path level must be a path parameter
Use lowercase separate words with hyphens for path segments
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /meta/commodity_groups/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
Every Second Path Level To Be Parameter
Lowercase words with hyphens
        (path: /meta/size_grids)
        No valid OAuth2 scope is defined for endpoint Get a list of size grids.
Every second path level must be a path parameter
Use lowercase separate words with hyphens for path segments
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /meta/size_grids/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
Every Second Path Level To Be Parameter
        (path: /meta/tags)
        No valid OAuth2 scope is defined for endpoint Get a list of tags.
Every second path level must be a path parameter
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /meta/tags/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
Every Second Path Level To Be Parameter
Pluralize Resource Names
        (path: /queue/configs/{config-id})
        No valid OAuth2 scope is defined for endpoint Get the details for the given config ID.
Every second path level must be a path parameter
Resource name 'queue' is not pluralized (but we are not sure)
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /queue/configs/{config-id}/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
Every Second Path Level To Be Parameter
Pluralize Resource Names
        (path: /queue/models)
        No valid OAuth2 scope is defined for endpoint Get all models to review for given merchant.
Every second path level must be a path parameter
Resource name 'queue' is not pluralized (but we are not sure)
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /queue/models/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
Every Second Path Level To Be Parameter
Pluralize Resource Names
        (path: /queue/models/{model-id})
        No valid OAuth2 scope is defined for endpoint Get one model by given model id
Every second path level must be a path parameter
Resource name 'queue' is not pluralized (but we are not sure)
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /queue/models/{model-id}/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
Every Second Path Level To Be Parameter
Pluralize Resource Names
        (path: /queue/summaries)
        No valid OAuth2 scope is defined for endpoint Get the queue summary for the given merchant, if specified, or the total for all merchants, if none is specified.
Every second path level must be a path parameter
Resource name 'queue' is not pluralized (but we are not sure)
        http://zalando.github.io/restful-api-guidelines/security/Security.html

Response As JSON Object
        (path: /queue/summaries/GET/200)
        Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
        https://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-always-return-json-objects-as-toplevel-data-structures-to-support-extensibility

Define and Assign Access Rights (Scopes)
        (path: /rejections)
        No valid OAuth2 scope is defined for endpoint Create a list of rejections and associate them with a given list of article configs
        http://zalando.github.io/restful-api-guidelines/security/Security.html


Found the following SHOULD violations
=====================================

Limit number of Resources
Use snake_case (never camelCase) for Query Parameters
        Number of paths (11) violates the limit of 8.
Query parameter 'merchant-id' does not use snake_case.
        http://zalando.github.io/restful-api-guidelines/resources/Resources.html#should-limit-number-of-resources


Summary:
========

MUST violations: 35
SHOULD violations: 5
COULD violations: 0
``` 

Again, very lengthy and not that convenient to process. 
as I think the only grouping that makes sense is grouping by rule name I propose not to add parameter "by which field to group". Also if we decide to implement it on server side it will make code simpler: each rule will return at most one violation, each violation will have list of paths, both title and description of violation will contain general info about rule itself, all path-specific data will be in path.

What do you think? Do you have other vision?

**Comment by fmueller** [comment]
Thanks @mkulak for your detailed thoughts. I have to admit that you are right, grouping by any field is not useful. The example you provided is exactly what I had in mind - grouping by rule and listing all paths per violation.

After your reasoning I think we should just incorporate this grouping in the payload, without any parameterization.

**Comment by netme** [comment]
@fmueller , @mkulak thanks for explanations, now it makes more sense. 

FYI, We have agreed with @mkulak that we'll do some pair programming on this topic.

**Comment by mkulak** [comment]
👍

**Pull request merged**
