### PR TITLE
Add Problem JSON Support

### LINKED ISSUE #60: Integrate Problem+Json for Error Messages
The zally api should respond with proper Problem+Json error messages

### PR DESCRIPTION
**Pull request by fmueller**
Fixes #60 

- added problem json spring library
- added problem json support for oauth2 issues
- improved violations controller: uses now same logic as github controller or detail controller -> if swagger is not valid a violation is created for it

### CODE REVIEW

**Comment by fmueller** [comment]
If merged, changes should be applied in CLI as well. See #56

**Comment by netme** [comment]
👍 Awesome!

Seems to be now CLI tool has issues (thanks to integration tests :-) ). I will adjust the tool. Meanwhile will use my admin permissions to merge this PR.

**Comment by fmueller** [comment]
@netme Weird is: locally integration tests are green... ^^

**Comment by netme** [comment]
@fmueller, I will still check it tonight to be 100% sure :-)

**Pull request merged**
