### PR TITLE
web-ui: proxy webpack dev server, remove generated javascript assets from version control

### PR DESCRIPTION
**Pull request by rbarilani**
* Improve development experience: start the server with nodemon watching just server code and reload the server, start webpack-dev-server as independent process watching just client code and refresh browser when something change, generate source-map.

* Remove generated bundle from version control (causing noise when PR)

* minor updates to README.md: reorder available environment variables, introduce DEV_* env variables

### CODE REVIEW

**Comment by netme** [comment]
"Moving" approval to Zappr

**Comment by netme** [comment]
👍

**Comment by netme** [comment]
👍

**Comment by fmueller** [comment]
@rbarilani Can you please resolve the conflicts? :)

**Comment by rbarilani** [comment]
@fmueller conflicts solved.

**Comment by rbarilani** [comment]
👍

**Comment by mfellner** [comment]
👍

**Pull request merged**
