### PR TITLE
#123 Make Zally Rules Compatible with Codacy, Part 1

### PR DESCRIPTION
**Pull request by netme**
Related to #123

### CODE REVIEW

**Comment by fmueller** [comment]
👍

**Comment by netme** [comment]
@fmueller , my proposal is to merge this and first see the impact on Codacy . We can continue with other files afterwards, most `D` and `C` grade issues should be already resolved.

**Comment by netme** [comment]
-37 issues according to [Codacy](https://www.codacy.com/app/zally/zally/pullRequest?prid=502160)

**Comment by fmueller** [comment]
👍

**Pull request merged**
