### PR TITLE
#546 Fixed links to guidelines from violations reports

### PR DESCRIPTION
**Pull request by roxspring**
#546 Fixed links to guidelines from violations reports

### CODE REVIEW

**Comment by netme** [comment]
Thanks @roxspring for your contribution. Maybe I'm missing something, but should we add a small test for that?

**Comment by netme** [comment]
👍

**Comment by netme** [comment]
Thanks again!

**Comment by mkulak** [comment]
👍

**Comment by netme** [comment]
@roxspring I would love to merge it, but now Codacy's PMD is not happy. 
Could you please add some fake assert statement to your test? 

More details: http://pmd.sourceforge.net/pmd-5.0.5/rules/java/junit.html#JUnitTestsShouldIncludeAssert

**Comment by netme** [comment]
Another option will be to use the following annotation

```java
@SuppressWarnings("PMD.JUnitTestShouldIncludeAssert")
```

**Comment by roxspring** [comment]
Suppressed the warning since the test is actually performing the check.

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
👍

**Comment by netme** [comment]
@maxim-tschumak could you please re-approve and merge it?

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
