### PR TITLE
ensure zalando it compliance #444

### LINKED ISSUE #444: Ensure IT-Compliance of Github Workflows
### User Story

**As a** development team
**I want** to be compliant to the mandatory rules
**So that** we do not violate the development rules
**And** the IT compliance department is happy with us.

### Description

We need to update the zapper configuration, so that the next compliance check does not show any violations.

Violated rule: 
- Every PR needs two approvals from Zalando employees

### PR DESCRIPTION
**Pull request by maschleg**
closes #444

### CODE REVIEW

**Comment by netme** [comment]
👍

**Comment by netme** [comment]
Looks good, but I'm not happy about that rules 😼

**Comment by maschleg** [comment]
yes sry we can't avoid the rules because we always get violations :/

**Comment by netme** [comment]
Last time we can merge it with only 1 +1 :-)

**Comment by netme** [comment]
@maschleg I know that it's not our initiative :-)

**Pull request merged**
