### PR TITLE
server: refact rest of the tests with DTOs (#433)

### LINKED ISSUE #433: Use DTOs in integration tests instead of JsonNode
The DTO beans were introduced in https://github.com/zalando-incubator/zally/issues/429 ✅

### PR DESCRIPTION
**Pull request by innokenty**
Closes #433

### CODE REVIEW

**Comment by innokenty** [comment]
Ready for merge.

**Comment by innokenty** [comment]
```
zappr/pr/specification — PR's body failed check 'contains-issue-number'
```
What does that mean?

**Comment by innokenty** [comment]
```
zappr/pr/specification — PR's body failed check 'contains-issue-number'
```
What does that mean?

**Comment by netme** [comment]
👍

**Comment by netme** [comment]
Haha, nice, I cannot approve pull requests anymore after #444 

@maxim-tschumak and @maschleg you need to help :-)

**Comment by netme** [comment]
@innokenty, we have introduced Zappr today. 

Now it requires all the commits and PR specification to be compliant meaning that the issue number should be specified. I've added an issue number to the PR description.

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
