### PR TITLE
server: refactor controllers a tiny bit + rename `violation` package (#429)

### PR DESCRIPTION
**Pull request by innokenty**
This PR is a preemptive refactoring before introducing more DTO bean classes that gonna replace `JsonNode`. Just thought it's easier to review & discuss separately.

Any better ideas for package names?

### CODE REVIEW

**Comment by innokenty** [comment]
That's some CI bug:
```

**Comment by innokenty** [comment]
test this please

**Comment by innokenty** [comment]
does this work with travis? 👆 
how can I trigger a rebuild?

**Comment by netme** [comment]
@innokenty it caused by these issues:

```
> Building 84% > :ktlinte/travis/build/zalando-incubator/zally/server/src/main/java/de/zalando/zally/rule/ExtensibleEnumRule.kt:9:1: Wildcard import
> Building 84% > :ktlinte/travis/build/zalando-incubator/zally/server/src/main/java/de/zalando/zally/rule/NoUnusedDefinitionsRule.kt:5:1: Wildcard import
> Building 84% > :ktlinte/travis/build/zalando-incubator/zally/server/src/main/java/de/zalando/zally/rule/NoUnusedDefinitionsRule.kt:8:1: Wildcard import
/home/travis/build/zalando-incubator/zally/server/src/main/java/de/zalando/zally/rule/UseProblemJsonRule.kt:5:1: Wildcard import
```

**Comment by netme** [comment]
Please reconfigure your IDE ;-)

**Comment by innokenty** [comment]
Damn, I did! I guess Kotlin import settings are separate from java!

**Comment by netme** [comment]
👍

**Pull request merged**
