### PR TITLE
342 Build Zally CLI Prototype in Go

### LINKED ISSUE #342: Create a Prototype of Zally CLI in Golang

### PR DESCRIPTION
**Pull request by netme**
Closes #342 

⚠️ Very early version of prototype. Tried to check how easy it will be to re-build Zally CLI in Golang. 

- Implements request to `GET http://localhost:8080/supported-rules`

### How to launch
1. Start Zally server locally with disabled auth
2. Set up `GOPATH` variable
3. Clone the repository to `$GOPATH/src/github.com/zalando-incubator/zally/`
4. `cd gocli/zally`
5. `go build`
6. `zally rules`

### CODE REVIEW

**Comment by fmueller** [comment]
@maschleg @maxim-tschumak Please have a look. WDYT?

@netme Very nice that you prototyped it.

**Comment by maschleg** [comment]
Looks like a straightforward command pattern 👍

**Comment by netme** [comment]
Thanks @maschleg and @fmueller for taking a look on it. There are still many things to improve like introducing proper packages, I will add that soon.

**Comment by maxim-tschumak** [comment]
I vote for switching to Golang, it suits much better our CLI use-case! Thanks, @netme!

**Comment by netme** [comment]
Thanks for checking, @maxim-tschumak . I will continue working on this prototype then and create few issues to port the existing functionality from the current CLI implementation.

**Comment by maxim-tschumak** [comment]
@netme feel free to assign beginner-friendly issues to me :)

**Comment by netme** [comment]
@maxim-tschumak sure, I think we are all beginners :-)

**Comment by fmueller** [comment]
I propose to implement go client in cli-go folder in parallel for java cli. This way we can migrate smoothly to new cli and keep the old one for bugfixes until the new cli is ready.

**Comment by netme** [comment]
@fmueller , sure, let me rename `gocli` to `cli-go` then. 
I will keep an internal folder `zally` still since Golang will use it for binary name.

**Comment by netme** [comment]
So maybe we can already merge it and continue development on issue-by-issue basis

**Comment by netme** [comment]
I've created few follow-up tickets: https://github.com/zalando-incubator/zally/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3ACLI-Go

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
