### PR TITLE
#62 try page error

### LINKED ISSUE #62: /try page cannot handle links to public github (only to GHE)
Steps:
1. open /try
2. paste https://raw.githubusercontent.com/Avalara/Swagger/master/avatax/batchsvc.yaml
3. hit "go"

Result:
Error page

Expected:
List of violations for this swagger file.

### PR DESCRIPTION
**Pull request by mkulak**
Closes #62

### CODE REVIEW

**Comment by netme** [comment]
:+1:

**Comment by netme** [comment]
👍

**Comment by mkulak** [comment]
I'm commenting to trigger zappr

**Comment by netme** [comment]
👍

**Pull request merged**
