### PR TITLE
fix: authorization token propagation (#1306)

### PR DESCRIPTION
**Pull request by tkrop**
#1306

Fix the forwarding of the authorization propagation URLs patterns during instantiation of the `DefaultContextFactory`.

### CODE REVIEW

**Comment by tkrop** [comment]
:+1:

**Review by vadeg — COMMENTED** [review]
Thank you!

I would simplify a little bit to reduce `lateinit` noise:
```kotlin
class ContextFactoryConfiguration {

    @Bean
    fun contextFactory(@Value("\${zally.propagateAuthorizationUrls:}") propagateAuthorizationUrls: List<Pattern>): DefaultContextFactory {
        return DefaultContextFactory(propagateAuthorizationUrls)
    }
}
```

**Comment by tkrop** [comment]
@vadeg **LOL** I would have left the original version before the refactoring that broke it to keep the code size even smaller (see https://github.com/zalando/zally/commit/6d9b7aaae9bcdc157d24c8332a45321eb64fdc5d#diff-1247b8e09fafc4c737a084e1d5efbf7840a79389e82d01e1b2d1fb25c376f00cL20). But for now lets go with the pull request to test this.

**Comment by vadeg** [comment]
@tkrop I have tested this already.

**Comment by vadeg** [comment]
👍

**Pull request merged**
