### PR TITLE
Fix case-sensitive common name matching

### PR DESCRIPTION
**Pull request by fmueller**
This PR fixes a possible bug: matching of common name rule is case-sensitive and has possible NPE in it.

### CODE REVIEW

**Comment by netme** [comment]
👍 Ship it!

**Comment by mkulak** [comment]
Y NO KOTLIN?
ᶘ ᵒᴥᵒᶅ

**Comment by fmueller** [comment]
@mkulak I don't saw the need.

**Comment by netme** [comment]
👍 Ship it

**Pull request merged**
