### PR TITLE
#125 Add codacy coverage reporting

### LINKED ISSUE #125: Introduce Test Coverage Tool
### Steps:
1. Find a good tool for measuring test coverage (preferable with GH integration)
2. Introduce it to the zally builds
3. Add a badge to `README.md`

### PR DESCRIPTION
**Pull request by netme**
Closes #125

### CODE REVIEW

**Comment by netme** [comment]
Current status: I have a problem with codacy API key. Need to encrypt it in Travis properly.

**Comment by fmueller** [comment]
@netme You can have a look at pazuzu-registry where I already did this integration. Hope this helps.

**Comment by netme** [comment]
@fmueller , thanks I will check.

**Comment by netme** [comment]
Things to do after merge:
- [ ] Remove a temporary API key from Codacy
- [ ] Save encrypted key to build against `master`

**Comment by fmueller** [comment]
👍

**Pull request merged**
