### PR TITLE
438: Fix WebUI links in Readme

### PR DESCRIPTION
**Pull request by netme**
Follow up on #438 

Addresses comments from @EduardoAC

### CODE REVIEW

**Comment by netme** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by EduardoAC** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
👍

**Comment by netme** [comment]
@maxim-tschumak could you please approve one more time? :-)

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
