### PR TITLE
CDP Integration: Fixing parse the PR number

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Relataed to #516

### CODE REVIEW

**Comment by ruiaraujo** [comment]
Doesn't CDP provide the PR number?

**Comment by maxim-tschumak** [comment]
@ruiaraujo CDP build is triggered only every change in PR **and** on merging into master. In the second case `CDP_PULL_REQUEST_NUMBER` variable is not set and we have to guess which one it was. Luckily, we now that the merge message (generated by Github) includes the number of PR.

**Comment by tkrop** [comment]
Huh, a rule based on compliance ... guess what fails first 😈.

**Comment by tkrop** [comment]
👍

**Comment by ruiaraujo** [comment]
@maxim-tschumak So even when we build on master, we want to tag by image by the last PR to be merged?

I guess this beckons a Feature request to CDP. 😄

**Comment by ruiaraujo** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
@ruiaraujo No, we just want to know, which files in the PR have been changed. In order to build and push only affected artifacts. (e.g. don't create a new version of zally-server if only web-ui has been changed in the PR)

**Pull request merged**
