### PR TITLE
Fix passing arguments in wrong order to assert.equal

### PR DESCRIPTION
**Pull request by topicus**
Ref: #520 

Change order in assert equals.

### Acceptance criteria
- Travis test passes

### QA Steps
- [ ] Start server api
- [ ] Run integration tests: go test -coverprofile=cover.out -covermode=atomic -v -tags=integration
- [ ] No error should be shown

### CODE REVIEW

**Comment by netme** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
👍

**Comment by netme** [comment]
@maxim-tschumak , could you please re-approve and merge it?

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
