### PR TITLE
Allow de-facto standard X-RateLimit-* headers

### PR DESCRIPTION
**Pull request by roxspring**
`HyphenatedHttpHeadersRule` (via `PatternUtils.isHyphenated()`) was being too conservative in what's permitted so relaxed it so that the X-RateLimit-* headers are acceptable.

Added de-facto standard X-RateLimit-* trio to whitelist in rules-config.conf so that other rules accept these specific examples.

Removed rules-config-test.conf from test tree since it was pointlessly duplicating rules-config.conf from the main tree.

Addresses #572

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
Thanks @roxspring!

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by roxspring** [comment]
@netme, @maschleg(, @maxim-tschumak)

I realize that you each likely have other things to do at Zalando and totally understand that Zally is only allowed to occupy a limited amount of your time, but please could I ask you to find a little more regular time for reviewing PRs from the outside world?

Currently we have 3 open pull requests sitting untouched for a week or more waiting for 1 or 2 approvals but no reason to think that's going to change any time soon. In the meantime its clear that some of you are finding time to coordinate on creating and merging internal PRs, highlighting that it's not simply a problem of having no time for the project. It's understandable that internal PRs move more quickly, but hopefully you can see that the disparity between the internal speed and external speed is frustrating and a little demoralizing as an external contributor.

Perhaps you could aim to review PRs within a week of being open? Maybe one of you is in a position to pull more Zalando employees in to spread the review load?? Even without the other suggestions, just getting into the habit of commenting e.g. "Busy right now, I'll aim to review this next Monday" would be extremely helpful in setting expectations and improving communications.

Thanks!!

Rob

**Comment by maxim-tschumak** [comment]
Thanks for the feedback Rob, I understand your concerns. We aim to reply fast to change requests and also PRs. @netme is normally faster than me, but he is in a well deserved holiday currently.

Nevertheless, I'll try to find some additional reviewers. Sorry for the inconvenience.

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by roxspring** [comment]
Doh - very nearly added a guess that maybe @netme was on holiday - definitely don't begrudge him that!

**Comment by mfellner** [comment]
👍

**Comment by tkrop** [comment]
👍

**Comment by maxim-tschumak** [comment]
I've fixed the conflicts in a local branch, here is the PR to merge: #585.

**Pull request closed without merging**
