### PR TITLE
web-ui: update test folder structure, fix linting, change coverage report output destination, change npm scripts naming

### LINKED ISSUE #227: web-ui: lint also test code
Actually the code containing test cases is not included when linting.

### LINKED ISSUE #233: web-ui: use suggested jest structure for tests
web-ui: use suggested jest structure for tests as discussed in this #228 pr.

...Linting should work also for test code related to #227

### PR DESCRIPTION
**Pull request by rbarilani**
web-ui: update test folder structure, fix linting, change coverage report output destination, change npm scripts naming.

close #233 
close #227

### CODE REVIEW

**Comment by rbarilani** [comment]
👍

**Comment by bhaskarmelkani** [comment]
👍

**Comment by rbarilani** [comment]
@maxim-tschumak can you merge this one?

**Comment by netme** [comment]
👍

**Pull request merged**
