### PR TITLE
#97 Migrate to Kotlin 1.1 and Make All Classes Open by Default

### PR DESCRIPTION
**Pull request by netme**
Related to #97

### CODE REVIEW

**Comment by netme** [comment]
@mkulak , @fmueller , I've moved refactoring part from #166 to a separate PR. 

Would be great if we can merge it soon, I will need it to prevent conflicts in #75 .

I will rebase #166 once this one will be merged.

**Comment by netme** [comment]
Since the commit in this PR is from @mkulak , giving my 👍 for the code

Will be really happy to see Kotlin 1.1 in production 🚀

**Comment by mkulak** [comment]
👍

**Comment by fmueller** [comment]
Good work @netme @mkulak :-)

**Pull request merged**
