### PR TITLE
#101 bump version of swagger-parser, fix and kotlinize test

### LINKED ISSUE #101: Upgrade to swagger-parser 1.0.25 breaks rule
There is an issue with newest version of swagger-parser library (1.0.25). One test breaks. Needs to be investigated and fixed.

### PR DESCRIPTION
**Pull request by mkulak**
Closes #101

### CODE REVIEW

**Comment by fmueller** [comment]
Great @mkulak 

Can you shortly point out what you've changed to fix the test?

And kudos for Kotlin :)

**Comment by mkulak** [comment]
@fmueller 
Initial version of this test had strong dependency on ordering of Swagger.paths (which has type Map). I just replaced it with order-independent assertion.

**Comment by fmueller** [comment]
👍

**Comment by fmueller** [comment]
👍

**Comment by fmueller** [comment]
👍

**Comment by netme** [comment]
👍

**Comment by mkulak** [comment]
👍

**Pull request merged**
