### PR TITLE
229 Do not use JPM to install coverage-reporter

### LINKED ISSUE #229: Fix failing jpm installation on Travis
Example of failing build: https://travis-ci.org/zalando-incubator/zally/builds/217354908

### PR DESCRIPTION
**Pull request by netme**
Closes #229

### CODE REVIEW

**Comment by netme** [comment]
`codacy-code-coverage` is running now. To send coverage report we need to merge it first.

**Comment by mkulak** [comment]
:+1:

**Comment by netme** [comment]
Let's check it! 🚀

**Comment by netme** [comment]
Master build: https://travis-ci.org/zalando-incubator/zally/builds/217603585

**Comment by netme** [comment]
Awesome, it works

**Pull request merged**
