### PR TITLE
Fix missing favicon

### PR DESCRIPTION
**Pull request by topicus**
Ref: #508 

### Description 
Adds icons for several devices.

### QA Steps
- [ ] Build and run the application
- [ ] Icon should be present in the tab

### Acceptance criteria
- [ ] Icon is present
- [ ] Icon background is transparent

### CODE REVIEW

**Comment by netme** [comment]
Awesome start!

**Comment by netme** [comment]
👍

**Comment by mkulak** [comment]
:+1:

**Comment by rbarilani** [comment]
👍

**Pull request merged**
