### PR TITLE
Add tests for Web-ui. #526

### LINKED ISSUE #526: Increase Test Coverage for Web UI
It is not looking too bad we are at 80%.

### Acceptance criteria
1. CLI test coverage is increased to 90%

### PR DESCRIPTION
**Pull request by ruiaraujo**
Closes #526.

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
I've retriggered Travis CI build

**Comment by ruiaraujo** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by rbarilani** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Pull request merged**
