### PR TITLE
Monitoring metrics instead of counters

### LINKED ISSUE #314: Use Meter metrics instead of Counters
**Current behavior**
Zally server collects counter metrics and exposes them via REST interface. However, counter metrics don't provide much meaning without a persistence and in the cloud setup (multiple stateless instances, auto-scaling, etc.).

**Expected behavior**
We should use [Meter](http://metrics.dropwizard.io/3.2.2/getting-started.html#gs-meters) metrics instead. They measure the rate of the events in specific time frames (e.g. 120 must violations in the last 15 minutes).

**Acceptance criteria**
- Counter metrics should be removed
- The `Meter` metrics should be collected for:
  - Each violation
  - Each violation type (must, should, could)
- Functional monitoring is set up (related to [internal-issue](https://github.bus.zalan.do/meta-api/management/issues/3))

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Fixes #314.

Example output of the metrics' endpoint:
```
{
   "meter.api-reviews.processed.fiveMinuteRate" : 0.6,
   "processors" : 4,
   "zmon.response.200.POST.api-violations.fifteenMinuteRate" : 0.6,
   "heap.used" : 265218,
   "zmon.response.200.POST.api-violations.oneMinuteRate" : 0.6,
   "meter.api-reviews.violations.type.COULD.oneMinuteRate" : 0.6,
   "meter.api-reviews.processed.oneMinuteRate" : 0.6,
   "httpsessions.max" : -1,
   "meter.api-reviews.violations.rule.nestedpathscouldberootpathsrule.meanRate" : 0.531373167528945,
   "meter.api-reviews.violations.rule.nestedpathscouldberootpathsrule.count" : 3,
   "httpsessions.active" : 0,
   "zmon.response.200.POST.api-violations.snapshot.999thPercentile" : 1133,
   "meter.api-reviews.violations.rule.use429headerforratelimitrule.count" : 3,
   "meter.api-reviews.violations.rule.useproblemjsonrule.count" : 3,
   "threads.daemon" : 21,
   "threads.peak" : 24,
   "meter.api-reviews.violations.type.COULD.count" : 3,
   "heap" : 4502016,
   "meter.api-reviews.violations.rule.useproblemjsonrule.oneMinuteRate" : 0.6,
   "meter.api-reviews.violations.rule.use429headerforratelimitrule.oneMinuteRate" : 0.6,
   "meter.api-reviews.violations.type.COULD.meanRate" : 0.531395313275535,
   "meter.api-reviews.violations.rule.use429headerforratelimitrule.meanRate" : 0.531360970155629,
   "meter.api-reviews.violations.type.MUST.count" : 6,
   "meter.api-reviews.requested.meanRate" : 0.465666983920202,
   "zmon.response.200.POST.api-violations.snapshot.mean" : 403,
   "threads.totalStarted" : 29,
   "instance.uptime" : 60702,
   "classes.unloaded" : 0,
   "zmon.response.200.POST.api-violations.meanRate" : 0.561400128131982,
   "classes" : 9035,
   "meter.api-reviews.violations.type.SHOULD.fiveMinuteRate" : 0.6,
   "meter.api-reviews.violations.rule.nestedpathscouldberootpathsrule.oneMinuteRate" : 0.6,
   "uptime" : 65660,
   "zmon.response.200.POST.api-violations.snapshot.95thPercentile" : 1133,
   "counter.status.200.api-violations" : 3,
   "meter.api-reviews.violations.rule.useproblemjsonrule.fiveMinuteRate" : 0.6,
   "meter.api-reviews.violations.rule.mediatypesrule.fiveMinuteRate" : 0.6,
   "mem.free" : 332285,
   "meter.api-reviews.violations.type.COULD.fiveMinuteRate" : 0.6,
   "meter.api-reviews.processed.meanRate" : 0.531412848206894,
   "meter.api-reviews.requested.fifteenMinuteRate" : 0.6,
   "nonheap.committed" : 68080,
   "gauge.response.api-violations" : 48,
   "nonheap.init" : 2496,
   "meter.api-reviews.violations.type.MUST.fiveMinuteRate" : 1.2,
   "zmon.response.200.POST.api-violations.snapshot.75thPercentile" : 1133,
   "nonheap" : 0,
   "zmon.response.200.POST.api-violations.snapshot.99thPercentile" : 1133,
   "heap.init" : 317440,
   "meter.api-reviews.violations.type.MUST.meanRate" : 1.06269810588946,
   "systemload.average" : 0.44,
   "meter.api-reviews.violations.rule.nestedpathscouldberootpathsrule.fifteenMinuteRate" : 0.6,
   "meter.api-reviews.violations.rule.use429headerforratelimitrule.fiveMinuteRate" : 0.6,
   "meter.api-reviews.violations.rule.useproblemjsonrule.fifteenMinuteRate" : 0.6,
   "meter.api-reviews.violations.type.SHOULD.meanRate" : 0.531380263078001,
   "zmon.response.200.POST.api-violations.snapshot.median" : 56,
   "meter.api-reviews.violations.rule.useproblemjsonrule.meanRate" : 0.531369193095302,
   "zmon.response.200.POST.api-violations.snapshot.stdDev" : 506,
   "threads" : 23,
   "meter.api-reviews.requested.fiveMinuteRate" : 0.6,
   "meter.api-reviews.violations.rule.mediatypesrule.fifteenMinuteRate" : 0.6,
   "meter.api-reviews.violations.type.SHOULD.fifteenMinuteRate" : 0.6,
   "meter.api-reviews.violations.rule.mediatypesrule.meanRate" : 0.53138623864711,
   "gc.ps_marksweep.time" : 107,
   "meter.api-reviews.violations.type.SHOULD.oneMinuteRate" : 0.6,
   "classes.loaded" : 9035,
   "gc.ps_scavenge.time" : 85,
   "meter.api-reviews.violations.rule.nestedpathscouldberootpathsrule.fiveMinuteRate" : 0.6,
   "heap.committed" : 597504,
   "zmon.response.200.POST.api-violations.snapshot.min" : 47,
   "meter.api-reviews.violations.rule.use429headerforratelimitrule.fifteenMinuteRate" : 0.6,
   "meter.api-reviews.violations.rule.mediatypesrule.count" : 3,
   "gc.ps_marksweep.count" : 2,
   "meter.api-reviews.violations.rule.mediatypesrule.oneMinuteRate" : 0.6,
   "meter.api-reviews.requested.count" : 3,
   "meter.api-reviews.violations.type.MUST.fifteenMinuteRate" : 1.2,
   "meter.api-reviews.requested.oneMinuteRate" : 0.6,
   "meter.api-reviews.violations.type.COULD.fifteenMinuteRate" : 0.6,
   "zmon.response.200.POST.api-violations.count" : 3,
   "nonheap.used" : 66475,
   "zmon.response.200.POST.api-violations.fiveMinuteRate" : 0.6,
   "zmon.response.200.POST.api-violations.snapshot.max" : 1133,
   "zmon.response.200.POST.api-violations.snapshot.98thPercentile" : 1133,
   "meter.api-reviews.violations.type.MUST.oneMinuteRate" : 1.2,
   "meter.api-reviews.violations.type.SHOULD.count" : 3,
   "gc.ps_scavenge.count" : 6,
   "meter.api-reviews.processed.count" : 3,
   "mem" : 663978,
   "meter.api-reviews.processed.fifteenMinuteRate" : 0.6
}
```

### CODE REVIEW

**Comment by fmueller** [comment]
👍

**Comment by fmueller** [comment]
👍

**Comment by netme** [comment]
Late 👍 :-)

**Comment by maxim-tschumak** [comment]
thanks for looking into @netme :)

**Pull request merged**
